# -*- coding: utf-8 -*-
"""aula4_imagineschool.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xYg7etrN7CxbzEffi_5Kaz1-mx_LbCr
"""

import getpass
import time

print("====================================================")
print(f"Iniciando a calculadora do usuário {getpass.getuser()}")
print("Operadores Aritméticos Existentes: ")
print("-> Operadores: ")
print("-> Opção 1: Adição (+)")
print("-> Opção 2: Subtração (-)")
print("-> Opção 3: Multiplicação (*)")
print("-> Opção 4: Divisão (/)")
print("====================================================")

i = 0

valores = []

while i<2: 
  valor = input(f"Digite o valor {i+1} para cálculo: ")
  valores.append(int(valor))
  i+=1

time.sleep(5)

while True:
  operador_matematico = input("Digite o operador Matemático:  ")

  #Condição 1 Divisão
  if operador_matematico in ['/', 'divisao', 'dividir']:
    resultado = valores[0] / valores[1]
    print(resultado)
    break

  elif operador_matematico in ['*', 'multiplicacao', 'multiplicar']:
    resultado = valores[0] * valores[1]
    print(resultado)
    break

  elif operador_matematico in ['+', 'soma', 'somar']:
    resultado = valores[0] + valores[1]
    print(resultado)
    break