# -*- coding: utf-8 -*-
"""calcular_imposto_salario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dmrZPFJQKtxKwucGkZHajzt7EbMB1mi
"""

codigo = int(input("Código do colaborador: "))
horas_trabalho = float(input("Número de horas trabalhadas: "))
valor_recebido_hora = float(input("Valor por hora R$: "))
idade_filhos = int(input("Número de filhos < 14: "))
idade = int(input("Idade: "))
tempo_servico = int(input("Tempo de Serviço do colaborador: "))
valor_salario_filho = float(input("Valor do sálario por filho em R$: "))


INSS = salario_bruto * desconto
salario_bruto = horas_trabalho * valor_recebido_hora
salario_familia = idade_filhos * valor_salario_filho
adicional = (salario_bruto * 2)/100 + (salario_bruto * 3.5)/ 100
salario_liquido = salario_bruto - desconto + adicional


if idade_filhos <= 14 and salario_familia >= 1556.94: 
   desconto = (valor_salario_filho * 8 )/ 100


elif salario_familia >= 1556.95 and salario_familia==2594.92:
   desconto = (valor_salario_filho * 9) / 100
   

elif salario_familia == 2594.93:
   desconto = (valor_salario_filho * 11) / 100
  


if salario_bruto == 1903.98:
  IR = salario_bruto * 0
  

elif salario_bruto >= 1903.99 and salario_bruto == 2826.66:
  IR  = (salario_bruto * 7.5)/100

elif salario_bruto >= 2826.66 and salario_bruto == 3751.05:
  IR = (salario_bruto * 15) / 100

elif salario_bruto >= 3751.06 and salario_bruto == 4664.68:
  IR = (salario_bruto * 22.5) / 100

else:
  IR = (salario_bruto * 27.5) / 100


print(f"Salário Família = {salario_familia}")
print(f"INSS = {INSS}")
print(f"IR = {IR}")


if idade >= 40:
  adicional = (salario_bruto * 2)/100

elif tempo_servico >= 15:
  adicional =  (salario_bruto * 3.5)/ 100

elif tempo_servico < 15 or tempo_servico > 5 and idade > 3:
  adicional =  (salario_bruto * 1.5)/ 100

else:
  adicional = (salario_bruto * 0.5) / 100


print(f"Código do colaborador: {codigo}")
print(f"Salário Bruto: {salario_bruto}")
print(f"Desconto: R${desconto}")
print(f"Adicional:  R${adicional}")
print(f"Salário Líquido R$ {salario_liquido}")

"""o IR ( Imposto de Renda) como segue:
Até 1903.98 – 0%
De 1903.99 até 2826.65 – 7,5%
De 2826.66 até 3751.05 – 15%
De 3751.06 até 4664.68 – 22.5%
Acima de 4664.68 – 27.5%
"""