# -*- coding: utf-8 -*-
"""funcao_range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enF99xfTHRiDiu_3u9TimtPhbwov4Gzl
"""

for item in range(10):
  print(item)


l = [10,12,14,16,18,20,30,40]
desc =[]
for k in range(len(l)-1,-1,-1):
   desc.append(l[k])
   print(desc)
